export enum CognitoStates {
  NOT_LOGGED_IN = 'NOT_LOGGED_IN',
  LOGGED_IN = 'LOGGED_IN',
  REQUIRE_MFA = 'REQUIRE_MFA',
  REQUIRE_CONFIRMATION = 'REQUIRE_CONFIRMATION',
  REQUIRE_NEW_PASSWORD = 'REQUIRE_NEW_PASSWORD'
}
