export enum LoginResponseCodes {
  SUCCESS = 'LOGIN_SUCCESS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  REQUIRE_PASSWORD_RESET = 'REQUIRE_PASSWORD_RESET',
  NOT_CONFIRMED = 'NOT_CONFIRMED',
  UNKNOWN = 'UNKNOWN',
  MFA_REQUIRED = 'MFA_REQUIRED'
}
